add some

diff --git a/觉得可以用的代码 b/觉得可以用的代码
--- a/觉得可以用的代码
+++ b/觉得可以用的代码
@@ -146,3 +146,206 @@ fi
 if grep -q Bash file
 then echo "File contains at least one occurrence of Bash."
 fi
+
+#  小技巧:
+#  如果你不能够确定一个特定的条件该如何进行判断,
+#+ 那么就使用if-test结构. 
+
+echo
+
+echo "Testing \"0\""
+if [ 0 ]      # zero
+then
+  echo "0 is true."
+else
+  echo "0 is false."
+fi            # 0 为真.
+
+/usr/bin/test, [ ], 和/usr/bin/[都是等价命令
+[[ ]]结构比[ ]结构更加通用. 这是一个扩展的test命令, 是从ksh88中引进的.
+在[[和]]之间所有的字符都不会发生文件名扩展或者单词分割, 但是会发生参数扩展和命令替换.
+使用[[ ... ]]条件判断结构, 而不是[ ... ], 能够防止脚本中的许多逻辑错误. 比如, &&, ||, <, 和> 操作符能够正常存在于[[ ]]条件判断结构中, 但是如果出现在[ ]结构中的话, 会报错.
+
+在if后面也不一定非得是test命令或者是用于条件判断的中括号结构( [ ] 或 [[ ]] ).
+
+  1 dir=/home/bozo
+  2 
+  3 if cd "$dir" 2>/dev/null; then   # "2>/dev/null" 会隐藏错误信息.
+  4   echo "Now in $dir."
+  5 else
+  6   echo "Can't change to $dir."
+  7 fi
+"if COMMAND"结构将会返回COMMAND的退出状态码.
+
+与此相似, 在中括号中的条件判断也不一定非得要if不可, 也可以使用列表结构.
+
+  1 var1=20
+  2 var2=22
+  3 [ "$var1" -ne "$var2" ] && echo "$var1 is not equal to $var2"
+  4 
+  5 home=/home/bozo
+  6 [ -d "$home" ] || echo "$home directory does not exist."
+
+  (( ))结构扩展并计算一个算术表达式的值. 如果表达式的结果为0, 那么返回的退出状态码为1, 或者是"假". 而一个非零值的表达式所返回的退出状态码将为0, 或者是"true". 这种情况和先前所讨论的test命令和[ ]结构的行为正好相反.
+
+    (( 5 > 4 ))                                      # 真
+    echo "Exit status of \"(( 5 > 4 ))\" is $?."     # 0
+
+7.2. 文件测试操作符
+如果下面的条件成立将会返回真.
+
+-e
+文件存在
+
+-a
+文件存在
+
+这个选项的效果与-e相同. 但是它已经被"弃用"了, 并且不鼓励使用.
+
+-f
+表示这个文件是一个一般文件(并不是目录或者设备文件)
+
+-s
+文件大小不为零
+
+-d
+表示这是一个目录
+
+-b
+表示这是一个块设备(软盘, 光驱, 等等.)
+
+-c
+表示这是一个字符设备(键盘, modem, 声卡, 等等.)
+
+-p
+这个文件是一个管道
+
+-h
+这是一个符号链接
+
+-L
+这是一个符号链接
+
+-S
+表示这是一个socket
+
+-t
+文件(描述符)被关联到一个终端设备上
+
+这个测试选项一般被用来检测脚本中的stdin([ -t 0 ]) 或者stdout([ -t 1 ])是否来自于一个终端.
+
+-r
+文件是否具有可读权限(指的是正在运行这个测试命令的用户是否具有读权限)
+
+-w
+文件是否具有可写权限(指的是正在运行这个测试命令的用户是否具有写权限)
+
+-x
+文件是否具有可执行权限(指的是正在运行这个测试命令的用户是否具有可执行权限)
+
+-g
+set-group-id(sgid)标记被设置到文件或目录上
+
+如果目录具有sgid标记的话, 那么在这个目录下所创建的文件将属于拥有这个目录的用户组, 而不必是创建这个文件的用户组. 这个特性对于在一个工作组中共享目录非常有用.
+
+-u
+set-user-id (suid)标记被设置到文件上
+
+如果一个root用户所拥有的二进制可执行文件设置了set-user-id标记位的话, 那么普通用户也会以root权限来运行这个文件. [1] 这对于需要访问系统硬件的执行程序(比如pppd和cdrecord)非常有用. 如果没有suid标志的话, 这些二进制执行程序是不能够被非root用户调用的.
+
+	      -rwsr-xr-t    1 root       178236 Oct  2  2000 /usr/sbin/pppd
+	      
+对于设置了suid标志的文件, 在它的权限列中将会以s表示.
+-k
+设置粘贴位
+
+对于"粘贴位"的一般了解, save-text-mode标志是一个文件权限的特殊类型. 如果文件设置了这个标志, 那么这个文件将会被保存到缓存中, 这样可以提高访问速度. [2] 粘贴位如果设置在目录中, 那么它将限制写权限. 对于设置了粘贴位的文件或目录, 在它们的权限标记列中将会显示t.
+
+	      drwxrwxrwt    7 root         1024 May 19 21:26 tmp/
+	      
+如果用户并不拥有这个设置了粘贴位的目录, 但是他在这个目录下具有写权限, 那么这个用户只能在这个目录下删除自己所拥有的文件. 这将有效的防止用户在一个公共目录中不慎覆盖或者删除别人的文件. 比如说/tmp目录. (当然, 目录的所有者或者root用户可以随意删除或重命名其中的文件.)
+-O
+判断你是否是文件的拥有者
+
+-G
+文件的group-id是否与你的相同
+
+-N
+从文件上一次被读取到现在为止, 文件是否被修改过
+
+f1 -nt f2
+文件f1比文件f2新
+
+f1 -ot f2
+文件f1比文件f2旧
+
+f1 -ef f2
+文件f1和文件f2是相同文件的硬链接
+
+!
+"非" -- 反转上边所有测试的结果(如果没给出条件, 那么返回真).
+
+例子 7-4. 测试那些断掉的链接文件
+
+  1 #!/bin/bash
+  2 # broken-link.sh
+  3 # 由Lee bigelow所编写 <ligelowbee@yahoo.com>
+  4 # 已经争得作者的授权引用在本书中.
+  5 
+  6 #一个纯粹的shell脚本用来找出那些断掉的符号链接文件并且输出它们所指向的文件.
+  7 #以便于它们可以把输出提供给xargs来进行处理 :)
+  8 #比如. broken-link.sh /somedir /someotherdir|xargs rm
+  9 #
+ 10 #下边的方法, 不管怎么说, 都是一种更好的办法:
+ 11 #
+ 12 #find "somedir" -type l -print0|\
+ 13 #xargs -r0 file|\
+ 14 #grep "broken symbolic"|
+ 15 #sed -e 's/^\|: *broken symbolic.*$/"/g'
+ 16 #
+ 17 #但这不是一个纯粹的bash脚本, 最起码现在不是.
+ 18 #注意: 谨防在/proc文件系统和任何死循环链接中使用!
+ 19 ##############################################################
+ 20 
+ 21 
+ 22 #如果没有参数被传递到脚本中, 那么就使用
+ 23 #当前目录. 否则就是用传递进来的参数作为目录
+ 24 #来搜索.
+ 25 ####################
+ 26 [ $# -eq 0 ] && directorys=`pwd` || directorys=$@
+ 27 
+ 28 #编写函数linkchk用来检查传递进来的目录或文件是否是链接, 
+ 29 #并判断这些文件或目录是否存在. 然后打印它们所指向的文件.
+ 30 #如果传递进来的元素包含子目录, 
+ 31 #那么把子目录也放到linkcheck函数中处理, 这样就达到了递归的目的.
+ 32 ##########
+ 33 linkchk () {
+ 34     for element in $1/*; do
+ 35     [ -h "$element" -a ! -e "$element" ] && echo \"$element\"
+ 36     [ -d "$element" ] && linkchk $element
+ 37     # 当然, '-h'用来测试符号链接, '-d'用来测试目录.
+ 38     done
+ 39 }
+ 40 
+ 41 #把每个传递到脚本的参数都送到linkchk函数中进行处理, 
+ 42 #检查是否有可用目录. 如果没有, 那么就打印错误消息和
+ 43 #使用信息.
+ 44 ################
+ 45 for directory in $directorys; do
+ 46     if [ -d $directory ]
+ 47 	then linkchk $directory
+ 48 	else 
+ 49 	    echo "$directory is not a directory"
+ 50 	    echo "Usage: $0 dir1 dir2 ..."
+ 51     fi
+ 52 done
+ 53 
+ 54 exit 0
+例子 28-1, 例子 10-7, 例子 10-3, 例子 28-3, 和例子 A-1也会演示文件测试操作的使用过程.
+
+注意事项
+[1]	
+在将suid标记设置到二进制可执行文件的时候, 一定要小心. 因为这可能会引发安全漏洞. 但是suid标记不会影响shell脚本.
+
+[2]	
+在当代UNIX系统中, 文件中已经不使用粘贴位了, 粘贴位只使用在目录中.
